// <auto-generated />
using System;
using Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260421145737_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Infrastructure.Entities.InventoryEntity", b =>
                {
                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ResourceItemId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("PlayerId", "ResourceItemId");

                    b.HasIndex("ResourceItemId");

                    b.ToTable("Inventory", (string)null);
                });

            modelBuilder.Entity("Infrastructure.Entities.PlayerConfigEntity", b =>
                {
                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<float>("MasterVolume")
                        .HasColumnType("real");

                    b.Property<float>("MusicVolume")
                        .HasColumnType("real");

                    b.Property<float>("SfxVolume")
                        .HasColumnType("real");

                    b.HasKey("PlayerId");

                    b.ToTable("PlayerConfig", (string)null);
                });

            modelBuilder.Entity("Infrastructure.Entities.PlayerEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Players", (string)null);
                });

            modelBuilder.Entity("Infrastructure.Entities.ResourceItemEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("IconPath")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("ResourceItems", (string)null);
                });

            modelBuilder.Entity("Infrastructure.Entities.StatsEntity", b =>
                {
                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<float>("Attack")
                        .HasColumnType("real");

                    b.Property<string>("ExtraStats")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Health")
                        .HasColumnType("real");

                    b.Property<float>("Luck")
                        .HasColumnType("real");

                    b.Property<float>("Speed")
                        .HasColumnType("real");

                    b.HasKey("PlayerId");

                    b.ToTable("Stats", (string)null);
                });

            modelBuilder.Entity("Infrastructure.Entities.InventoryEntity", b =>
                {
                    b.HasOne("Infrastructure.Entities.PlayerEntity", "Player")
                        .WithMany("Inventory")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Infrastructure.Entities.ResourceItemEntity", "ResourceItem")
                        .WithMany("InventoryEntries")
                        .HasForeignKey("ResourceItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");

                    b.Navigation("ResourceItem");
                });

            modelBuilder.Entity("Infrastructure.Entities.PlayerConfigEntity", b =>
                {
                    b.HasOne("Infrastructure.Entities.PlayerEntity", "Player")
                        .WithOne("Config")
                        .HasForeignKey("Infrastructure.Entities.PlayerConfigEntity", "PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("Infrastructure.Entities.StatsEntity", b =>
                {
                    b.HasOne("Infrastructure.Entities.PlayerEntity", "Player")
                        .WithOne("Stats")
                        .HasForeignKey("Infrastructure.Entities.StatsEntity", "PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("Infrastructure.Entities.PlayerEntity", b =>
                {
                    b.Navigation("Config");

                    b.Navigation("Inventory");

                    b.Navigation("Stats");
                });

            modelBuilder.Entity("Infrastructure.Entities.ResourceItemEntity", b =>
                {
                    b.Navigation("InventoryEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
